abshaadi/abshaadi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('', include('app.urls')),
]

abshaadi/app/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from app.views import home, dashboard, profiles_filters, site_management
from app.views.staff import package_management, user_management
#from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test

def staff_member_required(view_func=None, login_url='/page_403/'):
    """
    Decorator for views that checks that the user is logged in and is a staff
    member, redirecting to the login page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_active and u.is_staff,
        login_url=login_url
    )
    if view_func:
        return actual_decorator(view_func)
    return actual_decorator



# Authorization
urlpatterns = [
    path('',home.HomeView.as_view(), name="home"),
    path('page_403/',home.page_403, name="page_403" ),
    path('login/', home.LoginView.as_view(template_name = 'app/base/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'app/base/logout.html'), name = 'logout'),
    re_path(r'^accounts/*', RedirectView.as_view(pattern_name='login', permanent=True)),
    path('registration/', home.register_form, name='registration'),
    path('my_redirect_page/', home.my_redirect_page, name='my_redirect_page'),
    path('change_password/', home.change_password, name='change_password'),
]

# Site Managers
urlpatterns += [
    path('staff/religion-management/', never_cache(staff_member_required(site_management.ReligionManagementView.as_view())), name='religion_management'),
    path('load_religions_into_db/', never_cache(staff_member_required(site_management.load_religions_into_db)), name="load_religions_into_db"),
    path('add_religion/', never_cache(staff_member_required(site_management.add_religion)), name="add_religion"),
    path('staff/delete_religion/<int:ins>/', never_cache(staff_member_required(site_management.delete_religion)), name="delete_religion"),
    path('add_caste/', never_cache(staff_member_required(site_management.add_caste)), name="add_caste"),
    path('staff/delete_caste/<int:ins>/', never_cache(staff_member_required(site_management.delete_caste)), name="delete_caste"),
    path('staff/site_managers/load_countries/', never_cache(staff_member_required(site_management.add_countries_to_db)), name="add_countries_to_db"),
]

# Common Urls
urlpatterns += [
    path('get_states_dropdown/', never_cache(login_required(site_management.get_states_dropdown)), name="get_states_dropdown"),
    path('get_cities_dropdown/', never_cache(login_required(site_management.get_cities_dropdown)), name="get_cities_dropdown"),
    path('get_castes_dropdown/', never_cache(login_required(site_management.get_castes_dropdown)), name="get_castes_dropdown"),
]

# Dashboard
urlpatterns += [
    path('staff/dashboard/', never_cache(staff_member_required(dashboard.StaffDashboardView.as_view())), name="staff_dashboard"),
    path('dashboard/', never_cache(login_required(dashboard.UserDashboardView.as_view())), name="dashboard"),
]


# Profile
urlpatterns += [
    path('profile/', never_cache(login_required(profiles_filters.UserProfileView.as_view())), name="user_profile"),
    path('edit_personal_info/', never_cache(login_required(profiles_filters.edit_personal_info)), name="edit_personal_info"),
    path('upload_profile_pic/', never_cache(login_required(profiles_filters.upload_profile_pic)), name="upload_profile_pic"),
    path('upload_picture/', never_cache(login_required(profiles_filters.upload_profile_pic)), name="upload_picture"),
    path('Pay/', never_cache(login_required(profiles_filters.Pay)), name="Pay"),
    path('edit_other_detalis/', never_cache(login_required(profiles_filters.edit_other_detalis)), name="edit_other_detalis"),
    path('edit_summary_detalis/', never_cache(login_required(profiles_filters.edit_summary_detalis)), name="edit_summary_detalis"),
]


# Staff
urlpatterns += [
    path('staff/package_management/view/', never_cache(staff_member_required(package_management.PackageManagementView.as_view())), name="staff_package_management_view"),
    path('staff/user_management/users/view/', never_cache(staff_member_required(user_management.UserManagementView.as_view())), name="user_management_view"),
    path('staff/user_management/users/delete/<int:ins>/', never_cache(staff_member_required(user_management.delete_user)), name="delete_user"),
    path('staff/user_management/staff/view/', never_cache(staff_member_required(user_management.StaffManagementView.as_view())), name="staff_management_view"),
    path('staff/user_management/staff/add/', never_cache(staff_member_required(user_management.add_staff)), name="add_staff"),
]


# Search Pages
urlpatterns += [
    path('search_results/', never_cache(login_required(profiles_filters.MySearchView.as_view())), name="user_search_results"),
    path('save_partner_preferences/', never_cache(login_required(profiles_filters.save_partner_preferences)), name="save_partner_preferences")
]

# Partner Profile Views
urlpatterns += [
    path('connect_msg_save/', never_cache(login_required(profiles_filters.connect_message)), name="connect_msg_save"),
    path('profile_like/<int:to_user_id>/', never_cache(login_required(profiles_filters.profile_like)), name="profile_like"),
    path('partner_profile/<int:user_id>/', never_cache(login_required(profiles_filters.partner_profile_view)), name="partner_profile"),


]

#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abshaadi/app/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.conf import settings

import uuid
import os


#***********************************************************************
#
#***********************************************************************

class Religion(models.Model):
    religion_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
        unique = True,
    )
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.religion_name.capitalize()

    class Meta:
        verbose_name_plural = "Religions"


#***********************************************************************
#
#***********************************************************************

class Caste(models.Model):
    religion = models.ForeignKey(
        Religion,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    caste_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.caste_name.capitalize()

    class Meta:
        verbose_name_plural = "Religious Castes"

#***********************************************************************
#
#***********************************************************************

class Countries(models.Model):
    country_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.country_name.capitalize()

    class Meta:
        verbose_name_plural = "Countries List"

#***********************************************************************
#
#***********************************************************************

class Countries_States(models.Model):
    country = models.ForeignKey(
        Countries,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    state_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )    
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.state_name.capitalize()

    class Meta:
        verbose_name_plural = "States List"

#***********************************************************************
#
#***********************************************************************

class Countries_Cities(models.Model):
    country = models.ForeignKey(
        Countries,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    state_name = models.ForeignKey(
        Countries_States,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    city_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )    
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.city_name.capitalize()

    class Meta:
        verbose_name_plural = "Cities List"


#***********************************************************************
#
#***********************************************************************

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


#***********************************************************************
#
#***********************************************************************

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    
    online_now = models.BooleanField(
        db_index = True,
        default = False,
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


@receiver(post_delete, sender=CustomUser)
def delete_file(sender, instance, *args, **kwargs):

    path = os.path.join(settings.MEDIA_ROOT, str(instance.id))
    try:
        os.rmdir(path) 
    except:
        pass




#***********************************************************************
# PACKAGES
#***********************************************************************

class Package(models.Model): 

    TENURE_TYPE = (
        (1, "Years"),
        (2, "Months"),
        (3, "Weeks"),
    )

    IS_TRUE = ((True, 'YES'), (False, 'NO'))

    user = models.ForeignKey(
        CustomUser,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    package_name = models.CharField(
        max_length = 255,
        blank = False,
        null = False,
        unique = True,
    )
    
    value = models.IntegerField(
        db_index = True,
        null = False,
        blank = False,
    )
    
    tenure = models.IntegerField(
        db_index = True,
        null = False,
        blank = False,
    )
    
    tenure_types = models.IntegerField(
        default = 1,
        choices = TENURE_TYPE,
        db_index = True,
    )
    
    description = models.TextField(
        null = True,
        blank = True,
    )
    
    is_active = models.BooleanField(
        default = True,
        choices = IS_TRUE,
        db_index = True,
    )
    
    created_on = models.DateTimeField(
        auto_now_add = True,
        db_index = True,
        null = True,
        blank = True,
    )
    
    class Meta:
        verbose_name_plural = "Packages"
    
       
        
        
#***********************************************************************
# PROFILE
#***********************************************************************

class Profile(models.Model):
    user = models.ForeignKey(
        CustomUser,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    uid = models.CharField(
        max_length = 20,
        blank = True,
        null = True,
        db_index = True,
    )
    
    package = models.ForeignKey(
        Package,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.SET_NULL,
    )    
    
    fullname = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    MALE = 'M'
    FEMALE = 'F'
    
    gender_choices = ((MALE, 'Male'), (FEMALE, 'Female'))
    
    gender = models.CharField(
        max_length = 1,
        db_index = True,
        null = True,
        blank = False,
        choices = gender_choices,
    )
    
    looking_for_gender = models.CharField(
        max_length = 1,
        db_index = True,
        null = True,
        blank = False,
        choices = gender_choices,
    )
    
    
    father_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = True,
    )
    
    father_job = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    mother_job = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    mother_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = True,
    )
    
    siblings = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_male = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_female = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_elder = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_younger = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_married = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    dob = models.DateField(
        db_index = True,

abshaadi/app/templates/app/html_components/latest_matches.html
{% load static %}
<div class="card-header card-header-border" style="background-color:#ae09bd; color:#FFFFFF; margin-top:10px;">
    <strong>Latest Matches For You</strong>
</div>
<div class="card-body card-body-border" style="font-size:10px;">
	<div class="row" style="padding:10px;">
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
		<div class="col-md-3 col-sm-6 col-xs-12" style="padding:5px 10px 0px 10px;">
			<div class="card card-body-border">
				<img class="img" src="{% static 'images/user.png' %}" height="175px">
				<div style="padding:4px;">
					<label style="font-size:13px; display:block; margin-bottom:20px;">
						<span style="float:left; display:inline-block;">Priyanka S</span>
						<span style="float:right; display:inline-block;"> (23 yrs)</span>								
					</label>
					<label style="font-size:13px; display:block; line-height:30px; margin-bottom: 0px;">
						Kolkata
					</label>
				</div>
				<div style="padding:4px;" class="col-md-12 text-center">							
					<button type="button" class="btn bg-dark-green btn-sm" style="width: 80px" onclick="open_connect_modal(3)">
						<i class="mdi mdi-comment"></i> Connect
					</button>
					<button type="button" class="btn bg-dark-red btn-sm" style="width: 80px">
						<i class="mdi mdi-heart"></i> Like
					</button>
				</div>
			</div>
		</div>
		
	</div>
</div>

abshaadi/app/templates/app/html_components/packages_list.html
<div class="modal" tabindex="-1" role="dialog" id="packagesModal" style="background-color:#464e4ec2;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" role="document">
    
      <div class="modal-content">
      
          <div class="modal-header">
            <h5 class="modal-title">Upgrade Package</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          
          <div class="modal-body" style="font-size:80%">
            <div class="row">
            <form class="text-center border border-light p-5" action="{% url 'Pay' %}" method="POST">
            {% for package in packages_list %}
            
            {% csrf_token %}

              
                <div class="col-md-4 col-sm-12">
                  <div class="card" style="color:#FFF; background-color:#1f5f77;">
                    <div class="card-header">
                      <i class="mdi mdi-trophy mdi-24px" style="color:#ffd402"></i>
                      <span style="margin-top: 8px; position: absolute; line-height: 20px; display: inline; font-size: 17px; margin-left: 10px;">{{package.package_name}}</span>
                      <input type="submit" value="Pay with Razorpay" class="razorpay-payment-button">
                      <i class="mdi mdi-cart mdi-24px" data-buttontext="Pay with Razorpay" style="color: #ffd402; float: right; background-color: #09353c; padding: 0px 6px; border-radius: 100%; margin-top: -1px; cursor: pointer;"></i>
                      
                    </div>
                    <div class="card-body" style="color:#FFF; background-color:#1f5f77; height:300px; overflow:auto; padding:10px 22px;">
                      {{package.description}}
                    </div>
                    <div class="card-footer" style="color:#FFF; background-color:#1f5f77; overflow:auto; padding:10px 22px; font-size: 17px;">
                      <span>{{package.tenure}} {{package.get_tenure_types_display}}</span>
                      <span style="float:right;"><i class="mdi mdi-currency-inr">{{package.value}} only</i></span>
                    </div>
                  </div>
                </div>
                
              {% endfor %}
              
              <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_fX14iX9W836UYH"
            data-amount="50000" data-currency="INR" data-order_id="{{payment.id}}" data-buttontext="Pay with Razorpay"
            data-name="Professional Cipher" data-description="Django and Data Science"
            data-image="https://example.com/your_logo.jpg" data-prefill.name="PC" data-prefill.email="pc@studygyaan.com"
            data-theme.color="#F37254">
            </script>
            </form>
            </div>
          </div>
          
        </div>
        
    </div>
</div>

abshaadi/app/templates/app/html_components/recent_profiles.html
<div class="card-header card-header-border" style="background-color:#ae62e8; color:#FFFFFF;">
    <strong>Recent Profile Visitors</strong>
</div>
<div class="card-body card-body-border" style="padding:10px; height:300px;">
	<div class="col-md-3 col-sm-4 col-sx-6" style="height:150px;">
		gh
	</div>
</div>

abshaadi/app/templates/app/html_components/side_search_filters.html
{% load static %}

<!-- Filters -->

<div class="card-header card-header-border" style="margin-top:10px;">
    <strong style="margin-left:-10px;">Filters</strong>
    
	
	<button class="btn btn-sm btn-warning" style="float:right; margin-right: -10px; margin-top:-3px">
		<i class="mdi mdi-eye"></i> View Saved
	</button>
	
</div>

<div class="card-body card-body-border" style="font-size:10px;">
    <form method="post" action="{% url 'user_search_results' %}" id="search_filters_form">
		<div class="row" style="padding:10px">
		
			{% csrf_token %}
			<div class="col-12">
				<label>UID</label>
				<input type="text" class="form-control input-sm">
			</div>
			
			<div class="col-12" style="margin-top:10px;">
				<label>Religion</label>
				{{search_profile.l_religions}}
			</div>
			
			<div class="col-12 caste-div-spinner hide text-center" style="margin-top:10px;">
				<img class="img" src="{% static 'images/uploader_gifs/Spin-1s-24px.svg' %}">
			</div>
			
			<div class="col-12 caste-div hide" style="margin-top:10px;">
				<label>Caste/Denomination/Ethinicity</label>
				<select name="l_caste" class="form-control selectpicker castes_select" multiple></select>
			</div>
			
			<div class="col-12" style="margin-top:10px;">
				<label>Country</label>
				{{search_profile.l_countries}}
			</div>
			
			<div class="col-12 state-div-spinner hide text-center" style="margin-top:10px;">
				<img class="img" src="{% static 'images/uploader_gifs/Spin-1s-24px.svg' %}">
			</div>
			
			<div class="col-12 state-div hide" style="margin-top:10px;">
				<label>State</label>
				<select name="l_states" class="form-control selectpicker states_select" multiple></select>
			</div>

			<div class="col-12 city-div-spinner hide text-center" style="margin-top:10px;">
				<img class="img" src="{% static 'images/uploader_gifs/Spin-1s-24px.svg' %}">
			</div>

			<div class="col-12 city-div hide" style="margin-top:10px;">
				<label>City</label>
				<select class="form-control selectpicker city_select" name="l_cities" multiple></select>
			</div>
			
			<div class="col-12" style="margin-top:10px;">
				<label>Select Age</label>
				{{search_profile.aged_from}}
				{{search_profile.aged_to}}
			</div>
			
			<div class="col-12" style="margin-top:35px;">
				<div id="age_slider" style="width:94%"></div>
			</div>
			
			<div class="col-12" style="margin-top:20px;">
				<label>Complexion</label>
				<select></select>
			</div>
			
			<div class="col-12" style="margin-top:10px;">
				<label>Job</label>
				<select></select>
			</div>
			
			<div class="col-12" style="margin-top:10px;">
				<label>Qualification</label>
				<select></select>
			</div>
			
			<div class="col-12 text-center" style="margin-top:10px;">
				<button type="submit" class="btn btn-sm btn-warning">
					<i class="mdi mdi-search"></i> Search
				</button>
				<button style="margin-left:5px;" class="btn btn-sm btn-primary" type="button" 
					 data-target="#save_partner_preferences_modal" data-toggle="modal" data-backdrop="static" data-keyboard="false">
					<i class="mdi mdi-content-save"></i> Save
				</button>  
				
			</div>
		</div>
	</form>
</div>


{% include 'app/modal_forms/save_partner_search.html' %}

<script>

var csrf = '{{csrf_token}}';

</script>