abshaadi/abshaadi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('', include('app.urls')),
]

abshaadi/app/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from app.views import home, dashboard, profiles_filters, site_management
from app.views.staff import package_management, user_management
#from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test

def staff_member_required(view_func=None, login_url='/page_403/'):
    """
    Decorator for views that checks that the user is logged in and is a staff
    member, redirecting to the login page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_active and u.is_staff,
        login_url=login_url
    )
    if view_func:
        return actual_decorator(view_func)
    return actual_decorator



# Authorization
urlpatterns = [
    path('',home.HomeView.as_view(), name="home"),
    path('page_403/',home.page_403, name="page_403" ),
    path('login/', home.LoginView.as_view(template_name = 'app/base/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'app/base/logout.html'), name = 'logout'),
    re_path(r'^accounts/*', RedirectView.as_view(pattern_name='login', permanent=True)),
    path('registration/', home.register_form, name='registration'),
    path('my_redirect_page/', home.my_redirect_page, name='my_redirect_page'),
    path('change_password/', home.change_password, name='change_password'),
]

# Site Managers
urlpatterns += [
    path('staff/religion-management/', never_cache(staff_member_required(site_management.ReligionManagementView.as_view())), name='religion_management'),
    path('load_religions_into_db/', never_cache(staff_member_required(site_management.load_religions_into_db)), name="load_religions_into_db"),
    path('add_religion/', never_cache(staff_member_required(site_management.add_religion)), name="add_religion"),
    path('staff/delete_religion/<int:ins>/', never_cache(staff_member_required(site_management.delete_religion)), name="delete_religion"),
    path('add_caste/', never_cache(staff_member_required(site_management.add_caste)), name="add_caste"),
    path('staff/delete_caste/<int:ins>/', never_cache(staff_member_required(site_management.delete_caste)), name="delete_caste"),
    path('staff/site_managers/load_countries/', never_cache(staff_member_required(site_management.add_countries_to_db)), name="add_countries_to_db"),
]

# Common Urls
urlpatterns += [
    path('get_states_dropdown/', never_cache(login_required(site_management.get_states_dropdown)), name="get_states_dropdown"),
    path('get_cities_dropdown/', never_cache(login_required(site_management.get_cities_dropdown)), name="get_cities_dropdown"),
    path('get_castes_dropdown/', never_cache(login_required(site_management.get_castes_dropdown)), name="get_castes_dropdown"),
]

# Dashboard
urlpatterns += [
    path('staff/dashboard/', never_cache(staff_member_required(dashboard.StaffDashboardView.as_view())), name="staff_dashboard"),
    path('dashboard/', never_cache(login_required(dashboard.UserDashboardView.as_view())), name="dashboard"),
]


# Profile
urlpatterns += [
    path('profile/', never_cache(login_required(profiles_filters.UserProfileView.as_view())), name="user_profile"),
    path('edit_personal_info/', never_cache(login_required(profiles_filters.edit_personal_info)), name="edit_personal_info"),
    path('upload_profile_pic/', never_cache(login_required(profiles_filters.upload_profile_pic)), name="upload_profile_pic"),
    path('upload_picture/', never_cache(login_required(profiles_filters.upload_profile_pic)), name="upload_picture"),
    path('Pay/', never_cache(login_required(profiles_filters.Pay)), name="Pay"),
    path('edit_other_detalis/', never_cache(login_required(profiles_filters.edit_other_detalis)), name="edit_other_detalis"),
    path('edit_summary_detalis/', never_cache(login_required(profiles_filters.edit_summary_detalis)), name="edit_summary_detalis"),
]


# Staff
urlpatterns += [
    path('staff/package_management/view/', never_cache(staff_member_required(package_management.PackageManagementView.as_view())), name="staff_package_management_view"),
    path('staff/user_management/users/view/', never_cache(staff_member_required(user_management.UserManagementView.as_view())), name="user_management_view"),
    path('staff/user_management/users/delete/<int:ins>/', never_cache(staff_member_required(user_management.delete_user)), name="delete_user"),
    path('staff/user_management/staff/view/', never_cache(staff_member_required(user_management.StaffManagementView.as_view())), name="staff_management_view"),
    path('staff/user_management/staff/add/', never_cache(staff_member_required(user_management.add_staff)), name="add_staff"),
]


# Search Pages
urlpatterns += [
    path('search_results/', never_cache(login_required(profiles_filters.MySearchView.as_view())), name="user_search_results"),
    path('save_partner_preferences/', never_cache(login_required(profiles_filters.save_partner_preferences)), name="save_partner_preferences")
]

# Partner Profile Views
urlpatterns += [
    path('connect_msg_save/', never_cache(login_required(profiles_filters.connect_message)), name="connect_msg_save"),
    path('profile_like/<int:to_user_id>/', never_cache(login_required(profiles_filters.profile_like)), name="profile_like"),
    path('partner_profile/<int:user_id>/', never_cache(login_required(profiles_filters.partner_profile_view)), name="partner_profile"),


]

#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abshaadi/app/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.conf import settings

import uuid
import os


#***********************************************************************
#
#***********************************************************************

class Religion(models.Model):
    religion_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
        unique = True,
    )
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.religion_name.capitalize()

    class Meta:
        verbose_name_plural = "Religions"


#***********************************************************************
#
#***********************************************************************

class Caste(models.Model):
    religion = models.ForeignKey(
        Religion,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    caste_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.caste_name.capitalize()

    class Meta:
        verbose_name_plural = "Religious Castes"

#***********************************************************************
#
#***********************************************************************

class Countries(models.Model):
    country_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.country_name.capitalize()

    class Meta:
        verbose_name_plural = "Countries List"

#***********************************************************************
#
#***********************************************************************

class Countries_States(models.Model):
    country = models.ForeignKey(
        Countries,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    state_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )    
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.state_name.capitalize()

    class Meta:
        verbose_name_plural = "States List"

#***********************************************************************
#
#***********************************************************************

class Countries_Cities(models.Model):
    country = models.ForeignKey(
        Countries,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    state_name = models.ForeignKey(
        Countries_States,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    city_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )    
    
    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.city_name.capitalize()

    class Meta:
        verbose_name_plural = "Cities List"


#***********************************************************************
#
#***********************************************************************

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


#***********************************************************************
#
#***********************************************************************

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    
    online_now = models.BooleanField(
        db_index = True,
        default = False,
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


@receiver(post_delete, sender=CustomUser)
def delete_file(sender, instance, *args, **kwargs):

    path = os.path.join(settings.MEDIA_ROOT, str(instance.id))
    try:
        os.rmdir(path) 
    except:
        pass




#***********************************************************************
# PACKAGES
#***********************************************************************

class Package(models.Model): 

    TENURE_TYPE = (
        (1, "Years"),
        (2, "Months"),
        (3, "Weeks"),
    )

    IS_TRUE = ((True, 'YES'), (False, 'NO'))

    user = models.ForeignKey(
        CustomUser,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    package_name = models.CharField(
        max_length = 255,
        blank = False,
        null = False,
        unique = True,
    )
    
    value = models.IntegerField(
        db_index = True,
        null = False,
        blank = False,
    )
    
    tenure = models.IntegerField(
        db_index = True,
        null = False,
        blank = False,
    )
    
    tenure_types = models.IntegerField(
        default = 1,
        choices = TENURE_TYPE,
        db_index = True,
    )
    
    description = models.TextField(
        null = True,
        blank = True,
    )
    
    is_active = models.BooleanField(
        default = True,
        choices = IS_TRUE,
        db_index = True,
    )
    
    created_on = models.DateTimeField(
        auto_now_add = True,
        db_index = True,
        null = True,
        blank = True,
    )
    
    class Meta:
        verbose_name_plural = "Packages"
    
       
        
        
#***********************************************************************
# PROFILE
#***********************************************************************

class Profile(models.Model):
    user = models.ForeignKey(
        CustomUser,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )
    
    uid = models.CharField(
        max_length = 20,
        blank = True,
        null = True,
        db_index = True,
    )
    
    package = models.ForeignKey(
        Package,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.SET_NULL,
    )    
    
    fullname = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    MALE = 'M'
    FEMALE = 'F'
    
    gender_choices = ((MALE, 'Male'), (FEMALE, 'Female'))
    
    gender = models.CharField(
        max_length = 1,
        db_index = True,
        null = True,
        blank = False,
        choices = gender_choices,
    )
    
    looking_for_gender = models.CharField(
        max_length = 1,
        db_index = True,
        null = True,
        blank = False,
        choices = gender_choices,
    )
    
    
    father_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = True,
    )
    
    father_job = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    mother_job = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )
    
    mother_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = True,
    )
    
    siblings = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_male = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_female = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_elder = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_younger = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    sibling_married = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )
    
    dob = models.DateField(
        db_index = True,

abshaadi/app/templates/app/staff/index.html
<div class="row">

	<div class="col-md-12">
		<div class="card-header">
			<strong>Members Information</strong>
		</div>
		<div class="row">
			
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-primary text-center">
						<span class="mdi mdi-account icons" style="font-size:30px;color: #FFFFFF; position: relative; top: 5px;"></span>
					</div>
					<div class="col-8 bg-primary-light">
						<span class="icons-title">
							Registered
						</span>
						<span class="icons-counter">
							45
						</span>
					</div>
				</div>
			</div>
			
			<div class="col">
				<div class="row" style="padding:10px;">		
					<div class="col-4 bg-warning text-center">
						<span class="mdi mdi-account-star icons" style="font-size:30px;color: #FFFFFF; position: relative; top: 5px;"></span>
					</div>	
					<div class="col-8 bg-warning-light">						
						<span class="icons-title">
							Premium
						</span>
						<span class="icons-counter">
							45
						</span>
					</div>
				</div>
			</div>
			
			<div class="col">
				<div class="row" style="padding:10px;">		
					<div class="col-4 bg-success text-center">
						<span class="mdi mdi-account-network icons" style="font-size:30px;color: #FFFFFF; position: relative; top: 5px;"></span>
					</div>	
					<div class="col-8 bg-success-light">						
						<span class="icons-title">
							Active
						</span>
						<span class="icons-counter">
							45
						</span>
					</div>
				</div>
			</div>
			
			<div class="col">
				<div class="row" style="padding:10px;">		
					<div class="col-4 bg-danger text-center">
						<span class="mdi mdi-account-off icons" style="font-size:30px;color: #FFFFFF; position: relative; top: 5px;"></span>
					</div>	
					<div class="col-8 bg-danger-light">						
						<span class="icons-title">
							In-Active
						</span>
						<span class="icons-counter">
							45
						</span>
					</div>
				</div>
			</div>
		
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-pink text-center">
						<span class="mdi mdi-gender-female icons" style="font-size:30px;color: #FFFFFF; position: relative; top: 5px;"></span>
					</div>
					<div class="col-8 bg-pink-light">
						<span class="icons-title">
							Female
						</span>
						<span class="icons-counter">
							45
						</span>
					</div>
				</div>
			</div>
				
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-male text-center">
						<span class="mdi mdi-gender-male icons" style="font-size:30px;color: #FFFFFF; position: relative; top: 5px;"></span>
					</div>
					<div class="col-8 bg-male-light">
						<span class="icons-title">
							Male
						</span>
						<span class="icons-counter">
							45
						</span>
					</div>
				</div>
			</div>	
		</div>
	</div>
	
	
	<!-- EARNINGS SECTION -->
	
	<div class="col-md-12">
		<div class="card-header">
			<strong>Earnings</strong>
		</div>
		<div class="row">
			
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-earnings-icon text-center">
						<span class="mdi mdi-bank earnings-icons"></span>
					</div>
					<div class="col-8 bg-earnings">
						<span class="earnings-icons-title">
							Total Amount
						</span>
						<span class="earnings-icons-counter">
							Rs. 45900050
						</span>
					</div>
				</div>
			</div>
			
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-earnings-icon text-center">
						<span class="mdi mdi-treasure-chest earnings-icons"></span>
					</div>
					<div class="col-8 bg-earnings">
						<span class="earnings-icons-title">
							Today
						</span>
						<span class="earnings-icons-counter">
							Rs. 4590
						</span>
					</div>
				</div>
			</div>
			
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-earnings-icon text-center">
						<span class="mdi mdi-cash earnings-icons"></span>
					</div>
					<div class="col-8 bg-earnings">
						<span class="earnings-icons-title">
							This Month
						</span>
						<span class="earnings-icons-counter">
							Rs. 9000
						</span>
					</div>
				</div>
			</div>
			
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-earnings-icon text-center">
						<span class="mdi mdi-cash earnings-icons"></span>
					</div>
					<div class="col-8 bg-earnings">
						<span class="earnings-icons-title">
							Last 3 Months
						</span>
						<span class="earnings-icons-counter">
							Rs. 459000
						</span>
					</div>
				</div>
			</div>
			
			<div class="col">
				<div class="row" style="padding:10px;">						
					<div class="col-4 bg-earnings-icon text-center">
						<span class="mdi mdi-cash earnings-icons"></span>
					</div>
					<div class="col-8 bg-earnings">
						<span class="earnings-icons-title">
							This Year
						</span>
						<span class="earnings-icons-counter">
							Rs. 45900050
						</span>
					</div>
				</div>
			</div>
			
		</div>
	</div>
	
	<!-- PLANS SECTION -->
	
	<div class="col-md-12">
		<div class="card-header">
			<strong>Packages Information</strong>
		</div>
		<div class="row" style="padding:10px;">
			<div class="col-3 sidetab-col-left">
				<ul class="sidetabs">
					{% for package in packages %}
						<li id="id_package_counter_{{package.id}}" onclick="package_counters($(this))">{{ package.package_name|title }}</li>
					{% endfor %}
				</ul>
			</div>
			<div class="col-9 sidetab-col-right">
				<div class="container" style="padding:10px;">				
				
					<!-- Tabs -->
					{% for package in packages %}
						<div class="row package_counters" id="id_package_{{package.id}}">					
							<div class="col-8">
								<div class="row" style="margin-bottom:10px;">
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-pink text-center">
													<span class="mdi mdi-gender-female earnings-icons"></span>
												</div>
												<div class="col-8 bg-pink-light">
													<span class="earnings-icons-title">
														Total Registered
													</span>
													<span class="earnings-icons-counter">
														234
													</span>
												</div>
											</div>
										</div>
									</div>
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-male text-center">
													<span class="mdi mdi-gender-male earnings-icons"></span>
												</div>
												<div class="col-8 bg-male-light">
													<span class="earnings-icons-title">
														Total Registered
													</span>
													<span class="earnings-icons-counter">
														346
													</span>
												</div>
											</div>
										</div>
									</div>
								</div>
								
								<div class="row" style="margin-bottom:10px;">
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-pink text-center">
													<span class="mdi mdi-gender-female earnings-icons"></span>
												</div>
												<div class="col-8 bg-pink-light">
													<span class="earnings-icons-title">
														Registered This Year
													</span>
													<span class="earnings-icons-counter">
														23
													</span>
												</div>
											</div>
										</div>
									</div>
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-male text-center">
													<span class="mdi mdi-gender-male earnings-icons"></span>
												</div>
												<div class="col-8 bg-male-light">
													<span class="earnings-icons-title">
														Registered This Year
													</span>
													<span class="earnings-icons-counter">
														34
													</span>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="row" style="margin-bottom:10px;">
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-pink text-center">
													<span class="mdi mdi-gender-female earnings-icons"></span>
												</div>
												<div class="col-8 bg-pink-light">
													<span class="earnings-icons-title">
														Recently Expiring
													</span>
													<span class="earnings-icons-counter">
														23
													</span>
												</div>
											</div>
										</div>
									</div>
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-male text-center">
													<span class="mdi mdi-gender-male earnings-icons"></span>
												</div>
												<div class="col-8 bg-male-light">
													<span class="earnings-icons-title">
														Recently Expiring
													</span>
													<span class="earnings-icons-counter">
														34
													</span>
												</div>
											</div>
										</div>
									</div>
								</div>
								
								<div class="row">
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-pink text-center">
													<span class="mdi mdi-gender-female earnings-icons"></span>
												</div>
												<div class="col-8 bg-pink-light">
													<span class="earnings-icons-title">
														Expiring This Year
													</span>
													<span class="earnings-icons-counter">
														23
													</span>
												</div>
											</div>
										</div>
									</div>
									<div class="col">
										<div class="col-md-12 text-center">							
											<div class="row">
												<div class="col-4 bg-male text-center">
													<span class="mdi mdi-gender-male earnings-icons"></span>
												</div>
												<div class="col-8 bg-male-light">
													<span class="earnings-icons-title">
														Expiring This Year
													</span>
													<span class="earnings-icons-counter">
														34
													</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						
							<div class="col-4">
								<div class="col-md-12 bg-grey text-center">
									<span style="padding:10px; display:block;">
										<strong>PACKAGE DETAILS</strong>
									</span>
									<p style="margin-bottom:0px;">	
										{{package.description|safe}}
									</p>
								</div>
							</div>
							
						</div>
					{% endfor %}
					<!-- Tab1 -->
					
				</div>
			</div>			
		</div>
	</div>

</div>

abshaadi/app/templates/app/staff/package_management.html
<div class="row">

	<div class="col">
		<div class="card-header card-header-blue card-header-border">
			<strong>Package Information</strong>
			<button data-toggle="modal" data-target="#add_package_form" style="width:80px; float:right; margin-right:-16px; margin-top:-8px;" class="btn btn-info">
				<i class="mdi mdi-plus"></i> Add 
			</button>
		</div>
		<div class="card-body" style="padding-top:10px; background:none;">
			<table class="table table-bordered" style="margin:0px; padding:0px;">
				<tr class="text-center"  style="font-weight:bold; background-color:#ae62e8; color:#FFFFFF;">
					<td>Package Name</td>
					<td>Description</td>
					<td>Price</td>
					<td>Tenure</td>
					<td>Tenure Type</td>
					<td>Is Active</td>
					<td>Action</td>
				<tr>
				
				{% for package in packages %}
				<tr style="font-size:12px;  background-color:#FFF">
					<td style="padding:5px">{{ package.package_name }}</td>
					<td style="padding:5px">{{ package.description }}</td>
					<td style="padding:5px">{{ package.value }}</td>
					<td style="padding:5px">{{ package.tenure }}</td>
					<td style="padding:5px">{{ package.tenure_types }}</td>
					<td style="padding:5px" class="text-center">
						{% if package.tenure_types == True %}
						Yes
						{% elif package.tenure_types == False %}
						No
						{% endif %}
					</td>
					<td style="padding:5px" class="text-center">
						<i class="mdi mdi-pencil" data-toggle="modal"  data-target="#edit_package_model-{{forloop.counter}}"></i>
						<a href="{% url 'delete_package_management' package.id %}"><i class="mdi mdi-delete" style="color:#FF0000"></i></a>
					</td>
				<tr>
				{% endfor %}
			</table>
		</div>
    </div>
</div>    

{% include 'app/modal_forms/add_package_modal.html' %}

abshaadi/app/templates/app/staff/user_management.html
<div class="row">

	<div class="col">
		<div class="card-header card-header-blue card-header-border">
			<strong>Users Information</strong>			
		</div>
		<div class="card-body" style="padding-top:10px; background:none;">
			<table class="table table-bordered" style="margin:0px; padding:0px;">
				<tr class="text-center"  style="font-weight:bold; background-color:#ae62e8; color:#FFFFFF;">
					<td>Username</td>
					<td>Fullname</td>
					<td>Is Active</td>
					<td>Package</td>
					<td>Gender</td>
					<td>Looking For</td>
					<td>Action</td>
				<tr>
				{% for row in users %}
					<tr style="font-size:12px;  background-color:#FFF">
						<td style="padding:5px; line-height: 22px;">{{ row.user.email }}</td>
						<td style="padding:5px; line-height: 22px;">{{ row.fullname }}</td>
						<td style="padding:5px; line-height: 22px;">{{ row.user.is_active }}</td>
						<td style="padding:5px; line-height: 22px;">{{ row.package.package_name }}</td>
						<td style="padding:5px; line-height: 22px;">{{ row.get_gender_display }}</td>
						<td style="padding:5px; line-height: 22px;">{{ row.get_looking_for_gender_display }}</td>
						<td style="padding:5px; text-align:center;">
							<i class="mdi mdi-pencil" style="margin-right:15px; cursor:pointer; font-size:12px;"></i>
							<i class="mdi mdi-delete" onclick="delete_user({{row.user.id}})" style="cursor:pointer; color:#FF0000; font-size:15px;"></i>
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>
    </div>
</div>


{% include 'app/base/uploader_gif_modals.html' %}

<script>

var csrfmiddlewaretoken = '{{ csrf_token }}';

</script>